mysite/myauth/urls.py
from django.contrib.auth.models import User
from django.urls import path
from .views import (
    login_view,
    get_cookie_view,
    set_cookie_view,
    set_session_view,
    get_session_view,
    MyLogoutView,
    AboutMeView,
    RegisterView,
    FooBarView,
    UsersListView,
    UsersDetailsView,
    HelloView,
)
from django.contrib.auth.views import LoginView

app_name = "myauth"

urlpatterns = [
    # path('login/', login_view, name='login'),
    path(
        "login/",
        LoginView.as_view(
            template_name="myauth/login.html", redirect_authenticated_user=True
        ),
        name="login",
    ),
    path("hello/", HelloView.as_view(), name="hello"),
    path("logout/", MyLogoutView.as_view(), name="logout"),
    path("cookie/get/", get_cookie_view, name="cookie-get"),
    path("cookie/set/", set_cookie_view, name="cookie-set"),
    path("session/set/", set_session_view, name="session-set"),
    path("session/get/", get_session_view, name="session-get"),
    path("about-me/", AboutMeView.as_view(), name="about-me"),
    path("users-list/", UsersListView.as_view(), name="users-list"),
    path("user-details/<int:pk>", UsersDetailsView.as_view(), name="user-details"),
    path("register/", RegisterView.as_view(), name="register"),
    path("foo-bar/", FooBarView.as_view(), name="foo-bar"),
]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.contrib.sitemaps.views import sitemap
from .sitemaps import sitemaps
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)

urlpatterns = [
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    path("admin/", admin.site.urls),
    path("req/", include("requestdataapp.urls")),
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "api/schema/swagger/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger",
    ),
    path(
        "api/schema/redoc/",
        SpectacularRedocView.as_view(url_name="schema"),
        name="redoc",
    ),
    path("api/", include("myapiapp.urls")),
    path("blog/", include("BlogApp.urls")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
]
urlpatterns += i18n_patterns(
    path("myauth/", include("myauth.urls")),
    path("shop/", include("shopapp.urls")),
)

if settings.DEBUG:
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
    urlpatterns.extend(static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )

mysite/shopapp/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    ProductDetailsView,
    ShopIndexView,
    GroupsListView,
    ProductListView,
    OrderListView,
    OrdersDetailView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
    OrderCreateView,
    OrderUpdateView,
    OrderDeleteView,
    ProductsDataExportView,
    OrdersDataExportView,
    ProductViewSet,
    OrderViewSet,
    LatestProductsFeed,
    UserOrdersListView,
    UserOrdersExportView,
)

app_name = "shopapp"

routers = DefaultRouter()
routers.register("products", ProductViewSet)
routers.register("orders", OrderViewSet)

urlpatterns = [
    path("", ShopIndexView.as_view(), name="index"),
    path("api/", include(routers.urls)),
    path("groups/", GroupsListView.as_view(), name="groups_list"),
    path("products/", ProductListView.as_view(), name="products_list"),
    path("products/export/", ProductsDataExportView.as_view(), name="products-export"),
    path("products/create", ProductCreateView.as_view(), name="product_create"),
    path("products/<int:pk>/", ProductDetailsView.as_view(), name="product_details"),
    path(
        "products/<int:pk>/update", ProductUpdateView.as_view(), name="product_update"
    ),
    path(
        "products/<int:pk>/archive", ProductDeleteView.as_view(), name="product_delete"
    ),
    path("products/<int:pk>/delete", OrderDeleteView.as_view(), name="order_delete"),
    path("orders/", OrderListView.as_view(), name="orders_list"),
    path("orders/export/", OrdersDataExportView.as_view(), name="orders-export"),
    path("orders/create", OrderCreateView.as_view(), name="order_create"),
    path("orders/<int:pk>/", OrdersDetailView.as_view(), name="order_details"),
    path("orders/<int:pk>/update", OrderUpdateView.as_view(), name="order_update"),
    path("products/latest/feed/", LatestProductsFeed(), name="products-feed"),
    path(
        "users/<int:user_id>/orders/", UserOrdersListView.as_view(), name="user-orders"
    ),
    path(
        "users/<int:user_id>/orders/export/",
        UserOrdersExportView.as_view(),
        name="user-orders-export",
    ),
]

mysite/shopapp/models.py
from fileinput import filename

from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


def product_preview_directory_path(instanse: "Product", filename: str) -> str:
    return "products/product_{pk}/preview/{filename}".format(
        pk=instanse.pk,
        filename=filename,
    )


def get_deleted_user():
    return User.objects.get_or_create(username="deleted_user")[0]


class Product(models.Model):
    """
    Модель Product представляет товар, который можно продавать в интернет магазине.

    Заказы тут: :model:`shopapp. Order`
    """

    class Meta:
        ordering = ["name", "price"]
        verbose_name = _("Product")
        verbose_name_plural = _("Products")

    name = models.CharField(max_length=100, db_index=True)
    description = models.TextField(null=False, blank=True, db_index=True)
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    discount = models.SmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(
        User, on_delete=models.SET_DEFAULT, default=get_deleted_user, null=True
    )
    archived = models.BooleanField(default=False)
    preview = models.ImageField(
        null=True, blank=True, upload_to=product_preview_directory_path
    )

    def get_absolute_url(self):
        return reverse("shopapp:product_details", kwargs={"pk": self.pk})

    def __str__(self):
        return f"Product(pk={self.pk}, name={self.name!r})"


def product_images_directory_path(instanse: "ProductImage", filename: str) -> str:
    return "products/product_{pk}/images/{filename}".format(
        pk=instanse.product.pk,
        filename=filename,
    )


class ProductImage(models.Model):
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name="images"
    )
    image = models.ImageField(upload_to=product_images_directory_path)
    description = models.CharField(max_length=200, null=False, blank=True)


class Order(models.Model):
    class Meta:
        verbose_name = _("Order")
        verbose_name_plural = _("Orders")

    delivery_address = models.TextField(null=True, blank=True)
    promocode = models.CharField(max_length=20, null=False, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    products = models.ManyToManyField(Product, related_name="orders")
    receipt = models.FileField(null=True, upload_to="orders/receipts/")

mysite/shopapp/views.py
from timeit import default_timer
import logging
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    PermissionRequiredMixin,
    UserPassesTestMixin,
)
from django.contrib.auth.models import Group, User
from django.contrib.syndication.views import Feed
from django.core.cache import cache
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect, reverse
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import View
from django.shortcuts import get_object_or_404
from django.views.decorators.cache import cache_page
from django.views.generic import (
    TemplateView,
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from rest_framework.parsers import MultiPartParser
from rest_framework.request import Request
from rest_framework.response import Response

from .common import save_csv_products
from .models import Product, Order, ProductImage
from .forms import GroupForm, ProductForm
from rest_framework.viewsets import ModelViewSet
from .serializers import ProductSerializer, OrderSerializer
from rest_framework.filters import SearchFilter, OrderingFilter
from django_filters.rest_framework import DjangoFilterBackend
from drf_spectacular.utils import extend_schema, OpenApiResponse
from rest_framework.decorators import action
from csv import DictWriter

log = logging.getLogger(__name__)


class OrderViewSet(ModelViewSet):
    queryset = Order.objects.all()
    serializer_class = OrderSerializer
    filter_backends = [SearchFilter, DjangoFilterBackend, OrderingFilter]
    filterset_fields = [
        "delivery_address",
        "promocode",
        "created_at",
        "products",
        "user",
    ]
    search_fields = [
        "delivery_address",
        "products",
        "user",
    ]
    ordering_fields = [
        "delivery_address",
        "products",
        "user",
    ]


@extend_schema(description="Product views CRUD")
class ProductViewSet(ModelViewSet):
    """
    Набор представлений для действий над Product.
    Полный CRUD для сущностей товара.
    """

    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    filterset_fields = ["name", "description", "price", "discount", "archived"]
    filter_backends = [SearchFilter, DjangoFilterBackend, OrderingFilter]
    search_fields = ["name", "description"]
    ordering_fields = [
        "name",
        "price",
        "discount",
    ]

    @extend_schema(
        summary="Get one product by ID",
        description="Retrieves **product**, returns 404 if not found",
        responses={
            200: ProductSerializer,
            404: OpenApiResponse(description="Empty response, product by ID not found"),
        },
    )
    def retrieve(self, request, *args, **kwargs):
        return super().retrieve(*args, **kwargs)

    @method_decorator(cache_page(60 * 2))
    def list(self, *args, **kwargs):
        return super().list(*args, **kwargs)

    @action(methods=["get"], detail=False)
    def download_csv(self, request: Request):
        response = HttpResponse(content_type="text/csv")
        filename = "products-export.csv"
        response["Content-Disposition"] = f"attachment; filename={filename}"
        queryset = self.filter_queryset(self.get_queryset())
        fields = ["name", "description", "price", "discount"]
        queryset = queryset.only(*fields)
        writer = DictWriter(response, fieldnames=fields)
        writer.writeheader()
        for product in queryset:
            writer.writerow({field: getattr(product, field) for field in fields})
        return response

    @action(detail=False, methods=["post"], parser_classes=[MultiPartParser])
    def upload_csv(self, request: Request):
        products = save_csv_products(
            request.FILES["file"].file, encoding=request.encoding
        )
        serializer = self.get_serializer(products, many=True)
        return Response(serializer.data)


class ShopIndexView(View):
    # @method_decorator(cache_page(60 * 2))
    def get(self, request: HttpRequest) -> HttpResponse:
        products = [
            ("Laptop", 1999),
            ("Desktop", 2999),
            ("Smartphone", 999),
        ]
        context = {
            "time_running": default_timer(),
            "products": products,
            "items": 5,
        }
        print("shop index context", context)
        log.debug("Products for shop index: %s", products)
        log.info("Rendering shop index")
        return render(request, "shopapp/shop-index.html", context=context)


class GroupsListView(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        context = {
            "form": GroupForm(),
            "groups": Group.objects.prefetch_related("permissions").all(),
        }
        return render(request, "shopapp/groups-list.html", context=context)

    def post(self, request: HttpRequest):
        form = GroupForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect(request.path)


class ProductDetailsView(DetailView):
    template_name = "shopapp/products-details.html"
    # model = Product
    queryset = Product.objects.prefetch_related("images")
    context_object_name = "product"


class ProductListView(ListView):
    template_name = "shopapp/products-list.html"
    model = Product
    context_object_name = "products"
    queryset = Product.objects.filter(archived=False)


# @method_decorator(
#     permission_required("add_product", raise_exception=True), name="dispatch"
# )
class ProductCreateView(PermissionRequiredMixin, CreateView):
    permission_required = "add_product"
    model = Product
    fields = "name", "price", "description", "discount", "preview"
    success_url = reverse_lazy("shopapp:products_list")

    # def test_func(self):
    #     self.request.user.groups.filter(name='secret-group').exists()
    #     return self.request.user.is_superuser

    def form_valid(self, form):
        response = super().form_valid(form)
        form.instance.created_by = self.request.user
        return response


@method_decorator(
    permission_required("change_product", raise_exception=True), name="dispatch"
)
class ProductUpdateView(UserPassesTestMixin, UpdateView):
    def test_func(self):
        if self.request.user == Product.created_by or self.request.user.is_superuser:
            return True

    model = Product
    # fields = "name", "price", "description", "discount", "preview"
    template_name_suffix = "_update_form"
    form_class = ProductForm

    def get_success_url(self):
        return reverse(
            "shopapp:product_details",
            kwargs={"pk": self.object.pk},
        )

    def form_valid(self, form):
        response = super().form_valid(form)
        for image in form.files.getlist("images"):
            ProductImage.objects.create(
                product=self.object,
                image=image,
            )
        return response


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy("shopapp:products_list")

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.archived = True
        self.object.save()
        return HttpResponseRedirect(success_url)


class OrderCreateView(CreateView):
    model = Order
    fields = "user", "products", "delivery_address", "promocode"
    success_url = reverse_lazy("shopapp:orders_list")


class OrderListView(LoginRequiredMixin, ListView):
    template_name = "shopapp/orders_list.html"
    queryset = Order.objects.select_related("user").prefetch_related("products")


class OrdersDetailView(PermissionRequiredMixin, DetailView):
    permission_required = "shopapp.view_order"
    template_name = "shopapp/order_details.html"
    queryset = Order.objects.select_related("user").prefetch_related("products")


class UserOrdersListView(LoginRequiredMixin, ListView):
    template_name = "shopapp/user_orders.html"

    def get_object(self):
        pk = self.kwargs["user_id"]
        self.owner = get_object_or_404(User, id=pk)
        return self.owner

    def get_queryset(self):
        self.get_object()
        return (
            Order.objects.select_related("user")
            .filter(user=self.owner)
            .prefetch_related("products")
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["owner"] = self.owner
        context["orders"] = self.queryset
        return context


class OrderUpdateView(UpdateView):
    model = Order
    fields = "delivery_address", "promocode", "user", "products"
    template_name_suffix = "_update_form"

    def get_success_url(self):
        return reverse(
            "shopapp:order_details",
            kwargs={"pk": self.object.pk},
        )


class OrderDeleteView(DeleteView):
    model = Order
    success_url = reverse_lazy("shopapp:orders_list")


class ProductsDataExportView(View):
    def get(self, request: HttpRequest) -> JsonResponse:
        cache_key = "products_data_export"
        products_data = cache.get(cache_key)
        if products_data is None:
            products = Product.objects.order_by("pk").all()
            products_data = [
                {
                    "pk": product.pk,
                    "name": product.name,
                    "price": product.price,
                    "archived": product.archived,
                }
                for product in products
            ]
            cache.set(cache_key, products_data, 300)
        return JsonResponse({"products": products_data})


class OrdersDataExportView(UserPassesTestMixin, View):
    def test_func(self):
        if self.request.user.is_staff:
            return True

    def get(self, request: HttpRequest) -> JsonResponse:

mysite/shopapp/templates/shopapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>
    {% block title %}
      Base Title
    {% endblock %}
  </title>
</head>
<body>

{% block body %}
  Base body
{% endblock %}

</body>
</html>

mysite/shopapp/templates/shopapp/groups-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Groups List
{% endblock %}

{% block body %}
  <h1>Groups:</h1>
  <div>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Create</button>
    </form>
  </div>
  <div>
  {% if not groups %}
    <h3>No groups yet</h3>
  {% else %}
    <ul>

      {% for group in groups %}
          <li>
            <div>{{ group.name }}</div>
            <ul>
              {% for permission in group.permissions.all %}
                <li>
                  {{ permission.name }}
                  (<code>{{ permission.codename }}</code>)
                </li>
              {% endfor %}

            </ul>
          </li>
      {% endfor %}

    </ul>
  {% endif %}
  </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Confirm delete order
{% endblock %}

{% block body %}
    <h1>Are you sure you want to delete order {{ object.pk }}?</h1>
    <br>
    <div>
        <a href="{% url 'shopapp:order_details' pk=object.pk %}"
        >Back to order</a>
    </div>
    <br>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Delete</button>
        </form>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_details.html
{% extends "shopapp/base.html" %}

{% block title %}
    Order#{{ object.pk }} details
{% endblock %}

{% block body %}
    <h1>Order #{{ object.pk }}</h1>
<div>
          <p>Order by {% firstof object.user.first_name order.user.username %}</p>
          <p>Promocode: <code>{{ object.promocode }}</code></p>
          <p>Delivery address: {{ object.delivery_address }}</p>
          <div>
            Product in order:
            <ul>
              {% for product in object.products.all %}
                <li>{{ product.name }} for ${{ product.price }}</li>
              {% endfor %}

            </ul>
          </div>
        </div>
<div>
    <a href="{% url 'shopapp:order_update' pk=order.pk %}">Update order</a>
</div>
<div>
    <a href="{% url 'shopapp:order_delete' pk=order.pk %}">Delete order</a>
    </div>
<div>
    <a href="{% url 'shopapp:orders_list' %}">Back to orders</a>
</div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_update_form.html
{% extends 'shopapp/base.html'%}

{% block title %}
    Update order
{% endblock %}

{% block body %}
    <h1>Update order</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Update</button>
        </form>
    </div>
    <div>
        <a href="{% url 'shopapp:order_details' pk=order.pk %}"
        >Back to order # {{ object.pk }}</a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/orders_changelist.html
{% extends 'admin/change_list.html' %}

{% block object-tools-items %}
  {% load admin_urls %}
  <li>
    <a href="{% url 'admin:import_orders_csv' %}" class="addlink">
      Import CSV
    </a>
  </li>
  {{ block.super }}
{% endblock %}

mysite/shopapp/templates/shopapp/orders_list.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Orders list
{% endblock %}

{% block body %}
  <h1>Orders:</h1>
  {% if object_list %}
    <div>
      {% for order in object_list %}
        <div>
          <p><a href="{% url 'shopapp:order_details' pk=order.pk %}"
          >Details #{{ order.pk }}</a></p>
          <p>Order by {% firstof order.user.first_name order.user.username %}</p>
          <p>Promocode: <code>{{ order.promocode }}</code></p>
          <p>Delivery address: {{ order.delivery_address }}</p>
          <div>
            Product in order:
            <ul>
              {% for product in order.products.all %}
                <li>{{ product.name }} for ${{ product.price }}</li>
              {% endfor %}

            </ul>
          </div>

        </div>
      {% endfor %}

    </div>
  {% else %}
    <h3>No orders yet</h3>
  {% endif %}
  <div>
    <a href="{% url 'shopapp:order_create' %}"
    >Create a new order</a>
  </div>
{% endblock %}

mysite/shopapp/templates/shopapp/product_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Confirm archive {{ object.name }}
{% endblock %}

{% block body %}
    <h1>Are you sure you want to archive {{ object.name }}</h1>
    <br>
    <div>
        <a href="{% url 'shopapp:product_details' pk=object.pk %}"
        >Back to product</a>
    </div>
    <br>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Archive</button>
        </form>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/product_form.html
{% extends 'shopapp/base.html'%}

{% block title %}
    Create product
{% endblock %}

{% block body %}
    <h1>Create product</h1>
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
    <div>
        <a href="{% url 'shopapp:products_list' %}"
        >Back to products list</a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/products-details.html
{% extends 'shopapp/base.html' %}

{% load i18n %}

{% block title %}
  {% translate 'Product' %} #{{ product.pk }}
{% endblock %}

{% block body %}
  <h1>{% translate 'Product' %} <strong>{{ product.name }}</strong></h1>
  <div>
    <div>{% translate 'Description' %}: <em>{{ product.description }}</em></div>
    <div>{% translate 'Price' %}: {{ product.price }}</div>
    <div>{% translate 'Discount' %}: {{ product.discount }}</div>
    <div>{% translate 'Archived' %}: {{ product.archived }}</div>
    {% if product.preview %}
      <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
    {% endif %}
    <h3>{% translate 'Images' %}:</h3>
      {% blocktranslate count images_count=product.images|length %}
        There is only one image.
        {% plural %}
        There are {{ images_count }} images.
      {% endblocktranslate %}
    <div>
      {% for img in product.images.all  %}
        <div>
          <img src="{{ img.image }}" alt="{{ img.image.name }}">
          <div>{{ img.description }}</div>
        </div>
      {% empty %}
        <div>{% translate 'No images uploaded yet' %}</div>
      {% endfor %}
    </div>
  </div>
  {% url 'shopapp:product_update' pk=product.pk  %} as update_product_url
  {% url 'shopapp:product_delete' pk=product.pk %} as delete_product_url
  {% url 'shopapp:products_list' %} as product_list_url
  {% blocktranslate %}
  <div>
    <a href="{{ update_product_url }}">Update product</a>
  </div>
  <div>
    <a href="{{ delete_product_url }}">Archive product</a>
  </div>
  <div>
    <a href="{{ product_list_url }}">Back to products list</a>
  </div>
  {% endblocktranslate %}
{% endblock %}

mysite/shopapp/templates/shopapp/products-list.html
{% extends 'shopapp/base.html' %}

{% load i18n %}

{% block title %}
  {% translate 'Products list' %}
{% endblock %}

{% block body %}
  <h1>{% translate 'Products' %}:</h1>
  {% if products %}
  <div>
    {% blocktranslate count products_count=products|length %}
      There is only one product.
      {% plural %}
      There are {{ products_count }} products.
    {% endblocktranslate %}
  </div>
    <div>
    {% for product in products %}
      <div>
        <p><a href=" {% url 'shopapp:product_details' pk=product.pk %}"
        > {% translate 'Name' context 'product name' %}: {{ product.name }}</a></p>
        <p>{% translate 'Price' %}: {{ product.price }}</p>
        {% translate 'no discount' as no_discount %}
        <p>{% translate 'Discount' %}: {% firstof product.discount no_discount %}</p>
        {% if product.preview %}
          <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
        {% endif %}
      </div>
    {% endfor %}

    </div>
     <div>
    {% if perms.shopapp.add_product %}
      <a href="{% url 'shopapp:product_create' %}"
      >{% translate 'Create a new product' %}</a>
    {% endif %}
  </div>
  {% else %}
    {% url 'shopapp:product_create' %} as create_product_url
    {% blocktranslate %}
    <h3>No products yet</h3>
    <a href="{{ create_product_url }}"
    >Create a new one</a>
    {% endblocktranslate %}
  {% endif %}

{% endblock %}

mysite/shopapp/templates/shopapp/products_changelist.html
{% extends 'admin/change_list.html' %}

{% block object-tools-items %}
  {% load admin_urls %}
  <li>
    <a href="{% url 'admin:import_products_csv' %}" class="addlink">
      Import CSV
    </a>
  </li>
  {{ block.super }}
{% endblock %}

mysite/shopapp/templates/shopapp/shop-index.html
{% extends 'shopapp/base.html' %}
{% load cache %}

{% block title %}
  Shop Index
{% endblock %}


{% block body %}
  <h1>Hello Shop Index!</h1>

  <div>
    <ul>
      {% for name, price in products %}
        <li>{{ name }} ({{ name|length }}) for ${{ price }}</li>
        {% if name|length == 7 %}
          <span>Lucky product!</span>
        {% endif %}
      {% empty %}
        No products here
      {% endfor %}

    </ul>
  </div>

  <div>
    <strong>
      You have {{ items }} cherr{{ items|pluralize:'y,ies' }}
    </strong>
  </div>

  <div>
    Time running: {{ time_running }}
  </div>
  {% cache 100 lorem  %}
  <div>
    {% lorem 3 p random %}
  </div>
  {% endcache %}
{% endblock %}

mysite/shopapp/templates/shopapp/user_orders.html
{% extends 'shopapp/base.html' %}
{% load cache %}

{% block title %}
  {{owner.name}} orders list
{% endblock %}

{% block body %}
  <h1>Orders:</h1>
  {% if orders %}
    <div>
      {% for order in orders %}
        <div>
          <p><a href="{% url 'shopapp:order_details' pk=order.pk %}"
            {% cache 200 orders owner.id %}
              >Details #{{ order.pk }}</a></p>
              <p>Promocode: <code>{{ order.promocode }}</code></p>
              <p>Delivery address: {{ order.delivery_address }}</p>
              <div>
                Product in order:
                <ul>
                  {% for product in order.products.all %}
                    <li>{{ product.name }} for ${{ product.price }}</li>
                  {% endfor %}

                </ul>
              </div>
            {% endcache %}
        </div>
      {% endfor %}

    </div>
  {% else %}
    <h3>{{owner.name}} has no orders yet</h3>
  {% endif %}
  <div>
    <a href="{% url 'shopapp:order_create' %}"
    >Create a new order</a>
  </div>
{% endblock %}